import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/UseCases.module.css";
import Header from "../components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ControllerBar from "@/components/ControllerBar/ControllerBar";

const inter = Inter({ subsets: ["latin"] });

export default function UseCases() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header/>
        <div className={styles.content} data-testid="content">
          <div className={styles.title}>How people use Skool</div>
          <ControllerBar />
          <div className={styles.cardList}>
            <div className={styles.card}>
              <img className={styles.cardImage} src="https://assets.skool.com/skool/261fd46f69e6426aa595e243f823591f.png"></img>
              <div className={styles.cardContent}>
                <div>Online courses</div>
                <div >
                  Put your courses in the same place as your community. Let your students interact and collaborate in one place.
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <img className={styles.cardImage} src="https://assets.skool.com/skool/ee8af466750b46d2b7e72b131ee925ab.png"></img>
              <div className={styles.cardContent}>
                <div>Subscription memberships</div>
                <div >
                  Build a community and monetize by charging a monthly/annual subscription. Like a country club!
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <img className={styles.cardImage} src="https://assets.skool.com/skool/890f1c1ae5ce42acaf2abea87154b563.png"></img>
              <div className={styles.cardContent}>
                <div>Group funnels</div>
                <div >
                  Convert your audience to community to customers. Build interactive funnels that engage and convert.
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <img className={styles.cardImage} src="	https://assets.skool.com/skool/00e5ffa1f8dc48d288b91c498ca93bcb.png"></img>
              <div className={styles.cardContent}>
                <div>Coaching programs</div>
                <div >
                  Give your clients a home and improve their experience. Put all resources in 1-place, centralize communication.
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <img className={styles.cardImage} src="https://assets.skool.com/skool/c7000b95c7fa45c49f7136562ec47c8d.png"></img>
              <div className={styles.cardContent}>
                <div>Masterminds</div>
                <div >
                  Get your group in sync by putting everything in 1-place. Community, calls, events, recordings, DM's, broadcasts.
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <img className={styles.cardImage} src="https://assets.skool.com/skool/280f223b09b24ad5b210f86cf7a37032.png"></img>
              <div className={styles.cardContent}>
                <div>Support forums</div>
                <div >
                  Get your customers to support each other and build searchable help documentation organically over time.
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <img className={styles.cardImage} src="	https://assets.skool.com/skool/e665efd7aee849588f848c660b67191f.png"></img>
              <div className={styles.cardContent}>
                <div>SaaS / product development</div>
                <div >
                  Get feedback from your users to know what to build. Announce new features and get feedback immediately.
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <img className={styles.cardImage} src="	https://assets.skool.com/skool/e1105832ab1d4aee8c30c5e844066715.png"></img>
              <div className={styles.cardContent}>
                <div>Influencer / fan communities</div>
                <div >
                  Give your audience a place to hangout and connect. Deepen your relationship and get ideas from them.
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer/>
      </main>
    </>
  );
}
